### ISSUE TITLE
是否可以实现定位信息接入，实时轨迹等功能

### ISSUE THREAD

**Issue by yangmouren** [louliangsheng/hellobike#1]
目前了解过来途强可以接入，能实现实时定位信息显示，不知道哈啰智能芯是否也能读取接入？

**Comment by louliangsheng** [comment]
定位信息通过value_json.data.position获取,添加下面的yaml就可以生成一个sensor。
```
sensor:
  - platform: rest
    name: Hellobike Position
    unique_id: hellobike_position
    resource: https://a.hellobike.com/evehicle/api?rent.order.getRentBikeStatus
    method: POST
    payload: '{"bikeNo" : "xxx","token" : "xxx","action" : "rent.order.getRentBikeStatus"}'
    value_template: '{{ value_json.data.position }}'
```
然后通过自动化调用device_tracker.see服务将sensor转化成device_tracker实体。
```
alias: 哈啰智能芯位置转化
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.hellobike_position
condition: []
action:
  - service: device_tracker.see
    data_template:
      dev_id: hellobike
      gps:
        - "{{ states('sensor.hellobike_position').split(',')[1] }}"
        - "{{ states('sensor.hellobike_position').split(',')[0] }}"
mode: single
````

**Comment by louliangsheng** [comment]
可以将上面的sensor拆分，sensor.hellobike_position_latitude以及states.sensor.hellobike_position_longitude，然后通过device_tracker.see服务转化成device_tracker实体。
```
service: device_tracker.see
data_template:
  dev_id: hellobike
  gps:
    - '{{ states.sensor.hellobike_position_latitude }}'
    - '{{ states.sensor.hellobike_position_longitude }}'
````
